### ISSUE TITLE
似乎沒有成功建立 bulid

### ISSUE THREAD

**Issue by gingerch** [familytalktw/familytalktw.github.io#1]
![螢幕快照 2019-08-28 下午2 36 06](https://user-images.githubusercontent.com/2968241/63831461-440b0000-c9a1-11e9-8e91-d408432153ef.png)

![螢幕快照 2019-08-28 下午2 42 35](https://user-images.githubusercontent.com/2968241/63831859-2a1ded00-c9a2-11e9-8601-87d9a778991e.png)

**Comment by familytalktw** [comment]
經確認，是 20190822.yml 內有語法錯誤，分別是34行和49行縮排問題，已於 4c8a657 修正

**Comment by familytalktw** [comment]
經確認，是 20190822.yml 內有語法錯誤，分別是34行和49行縮排問題，已於 dba1f4d 修正

**Comment by familytalktw** [comment]
http://www.familytalk.tw/records 運作正常了，關閉本則 issue
